# Used the following yaml as reference
# https://github.com/xiaozhuai/test_github_actions/blob/1487cc732bf08a4e5a31b3551a3db7542730f8ae/.github/workflows/build-every-commit.yml
name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]
        compiler:
          - llvm-13.0.0
          - gcc-11.0.0
          - gcc-10.0.0
          - gcc-9.0.0
          # you can specify the version after `-` like `llvm-13.0.0`.
        include:
          - os: "windows-2022"
            compiler: "msvc"
    runs-on: ${{ matrix.os }}
    env:
      CPM_SOURCE_CACHE: ~/.cpm/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cpm/

          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
      
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true
          cppcheck: true
          clangtidy: true

      - name: Configure build environment
        run: |
          mkdir build
          cd build
          cmake ../ -GNinja
    
      - name: Build Tests
        run: |
          cd build
          cmake --build . --target move-mm-tests -j16
      
      - name: Run Tests
        run: ./build/tests/move-mm-tests -r junit > tests/move-mm-tests.xml
      
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        with:
          files: tests/**/*.xml